CREATE TABLE public."user" (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	email varchar NOT NULL,
	"password" varchar NOT NULL,
	CONSTRAINT user_pkey PRIMARY KEY (id)
);

INSERT INTO public."user" (email,"password") VALUES
	 ('mizu@example.com','12345'),
	 ('jak@example.com','12345'),
	 ('k.inuki@haguruma.co.jp','2004kei012'),
	 ('generation.o.k.d.1109@gmail.com','okuda1109'),
	 ('ryo.mizuno502@gmail.com','ryomiz0827'),
	 ('ttakehisasp18k@gmail.com','@aayV-gaw-cz3b!7'),
	 ('iwaking43@gmail.com','nfZhR27J!'),
	 ('june.milkyway.d@gmail.com','Abc@123'),
	 ('okahanako09875@gmail.com','oka875Ei5'),
	 ('iwaking43@gmail.com','test1234'),
	 ('yukinkopen@gmail.com','rct20tpsct21!'),
	 ('ttakuma@example.com','12345678'),
	 ('atsushi.isai131@gmail.com','19950623'),
	 ('dmasa.ike@gmail.com','9uJarC3RirV3'),
	 ('dende@example.com','dende0206'),
	 ('koutaroutohi@gmail.com','ToraisetechhI'),
	 ('tearpeace@live.com','koufukuno01'),
	 ('s7660206@gmail.com','qazwsx'),
	 ('yspps@hoge.com','yspps'),
	 ('kuboryu-test@gmail.com','nandemo-memo-app'),
	 ('masaki.shimadu@gmail.com','masaki6549'),
	 ('iwktak@gmail.com','12345'),
	 ('zm73aym@gmail.com','U5qQxRW'),
	 ('loseworld9731.work@gmail.com','password'),
	 ('ayn3016@gmail.com','usako0127'),
	 ('nobuharayuki422@gmail.com','nobuyuki422');
